name: Release
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Publish
        run: cargo publish --token ${CRATES_TOKEN} --dry-run
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
